title: Serendeepia
#google_analytics:
theme: jekyll-theme-minimal
collections:
  careers:
    output: true
  success_stories:
    output: true
  products:
    output: true
  slides:
    output: true
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '.idea'
  - '.gitignore'
  - 'CODEOWNERS'